### ISSUE TITLE
Support application/json as a syntax type

### ISSUE THREAD

**Issue by Xiol** [Lee303/gopaste#2]
Hi,

I'm unable to use `application/json` as a syntax type, instead it must be `application/ld+json`. Would be nice to be able to use `application/json` even if that is just an alias for the other type.

```
❯ python3 graph_ids.py | gopaste -syntax "application/json"
failed to add paste: unsuccessful request: statuscode=401 data=Invalid syntax
❯ python3 graph_ids.py | gopaste -syntax "application/ld+json"
https://p.lee.io/...
```

**Comment by 0x4c6565** [comment]
Fixed - added alias
